# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-5dc0366b-cb17-4528-97eb-46e4bcf4a09e";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-5dc0366b-cb17-4528-97eb-46e4bcf4a09e".device = "/dev/disk/by-uuid/5dc0366b-cb17-4528-97eb-46e4bcf4a09e";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-5dc0366b-cb17-4528-97eb-46e4bcf4a09e";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-5dc0366b-cb17-4528-97eb-46e4bcf4a09e";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/438E-A9ED";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-7428c180-79d2-469a-83e0-39d1cb4366c5";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
